/**
 * Curated food-category thumbnails, keyed by normalized category name.
 *
 * GENERATED FILE â€” do not edit by hand. Regenerate with:
 *   node scripts/generateFoodImageMap.mjs
 *
 * Images are Wikimedia Commons thumbnails returned by the pageimages API, which
 * only yields a thumbnail for a file that exists. Entries confirmed dead (404/410)
 * are dropped at generation time. Re-check anytime with:
 *   node scripts/verifyFoodImageMap.mjs
 *
 * Generated 2026-09-04 with 313 categories.
 */
export const CURATED_FOOD_IMAGES: Record<string, string> = {
  'pasta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/330px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg',
  'spaghetti': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Spaghettoni.jpg/330px-Spaghettoni.jpg',
  'macaroni': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Macaroni2.jpg/330px-Macaroni2.jpg',
  'lasagna': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Lasagne_-_stonesoup.jpg/330px-Lasagne_-_stonesoup.jpg',
  'noodles': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Dalian_Liaoning_China_Noodlemaker-01.jpg/330px-Dalian_Liaoning_China_Noodlemaker-01.jpg',
  'ramen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg/330px-Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg',
  'rice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Meshi_001.jpg/330px-Meshi_001.jpg',
  'brown rice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Reis_-_Sorte_C_voll.jpg/330px-Reis_-_Sorte_C_voll.jpg',
  'white rice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Half_a_cup_of_rice._Brown_rice_is_the_best_choice.JPG/330px-Half_a_cup_of_rice._Brown_rice_is_the_best_choice.JPG',
  'fried rice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Koh_Mak%2C_Thailand%2C_Fried_rice_with_seafood%2C_Thai_fried_rice.jpg/330px-Koh_Mak%2C_Thailand%2C_Fried_rice_with_seafood%2C_Thai_fried_rice.jpg',
  'quinoa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Reismelde.jpg/330px-Reismelde.jpg',
  'couscous': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg/330px-Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg',
  'bread': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/330px-Korb_mit_Br%C3%B6tchen.JPG',
  'bagel': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Bagel_with_sesame_3.jpg/330px-Bagel_with_sesame_3.jpg',
  'toast': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Toast-3.jpg/330px-Toast-3.jpg',
  'tortilla': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Stacks_of_corn_tortillas_and_flour_tortillas%2C_with_the_top_one_rolled%2C_side_view_%282%29.jpg/330px-Stacks_of_corn_tortillas_and_flour_tortillas%2C_with_the_top_one_rolled%2C_side_view_%282%29.jpg',
  'croissant': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Croissant-Petr_Kratochvil.jpg/330px-Croissant-Petr_Kratochvil.jpg',
  'pizza': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/330px-Pizza-3007395.jpg',
  'hamburger': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/RedDot_Burger.jpg/330px-RedDot_Burger.jpg',
  'sandwich': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bacon%2C_lettuce%2C_tomato%2C_and_avocado.jpg/330px-Bacon%2C_lettuce%2C_tomato%2C_and_avocado.jpg',
  'hot dog': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hot_dog_with_mustard.png/330px-Hot_dog_with_mustard.png',
  'taco': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/330px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg',
  'burrito': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Burrito.JPG/330px-Burrito.JPG',
  'wrap': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Smoked_chicken_and_avocado_wrap.jpg/330px-Smoked_chicken_and_avocado_wrap.jpg',
  'sushi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/330px-Sushi_platter.jpg',
  'curry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Taj_Mahal_-_Lamb_Curry_Madras.jpg/330px-Taj_Mahal_-_Lamb_Curry_Madras.jpg',
  'soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Asparagus_soup_%28spargelsuppe%29.jpg/330px-Asparagus_soup_%28spargelsuppe%29.jpg',
  'stew': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lamb-stew.jpg/330px-Lamb-stew.jpg',
  'salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Salad_platter.jpg/330px-Salad_platter.jpg',
  'chicken': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg/330px-Max%27s_Roasted_Chicken_-_Evan_Swigart.jpg',
  'fried chicken': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Fried-Chicken-Set.jpg/330px-Fried-Chicken-Set.jpg',
  'chicken wings': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Buffalo_wings-01.jpg/330px-Buffalo_wings-01.jpg',
  'turkey': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Thanksgiving_Turkey.jpg/330px-Thanksgiving_Turkey.jpg',
  'beef': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Standing-rib-roast.jpg/330px-Standing-rib-roast.jpg',
  'steak': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Steak_with_shitaki_mushrooms.jpg/330px-Steak_with_shitaki_mushrooms.jpg',
  'pork': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Schweinebauch-2.jpg/330px-Schweinebauch-2.jpg',
  'bacon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Made20bacon.png/330px-Made20bacon.png',
  'ham': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Ham_%284%29.jpg/330px-Ham_%284%29.jpg',
  'sausage': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Wurstplatte.jpg/330px-Wurstplatte.jpg',
  'lamb': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Lamb_meat_%281%29.jpg/330px-Lamb_meat_%281%29.jpg',
  'fish': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Fish_stuffed_with_Thai_herbs.jpg/330px-Fish_stuffed_with_Thai_herbs.jpg',
  'salmon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Sashimi_-_Maguro_Restaurant%2C_Bangna%2C_Bangkok_%2844856596864%29.jpg/330px-Sashimi_-_Maguro_Restaurant%2C_Bangna%2C_Bangkok_%2844856596864%29.jpg',
  'tuna': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Chicharros_en_escabeche.jpg/330px-Chicharros_en_escabeche.jpg',
  'shrimp': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Spicy_fried_King_Prawns.jpg/330px-Spicy_fried_King_Prawns.jpg',
  'egg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Huevo_frito.jpg/330px-Huevo_frito.jpg',
  'omelette': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg/330px-Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg',
  'milk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glass_of_Milk_%2833657535532%29.jpg/330px-Glass_of_Milk_%2833657535532%29.jpg',
  'cheese': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cheese_platter.jpg/330px-Cheese_platter.jpg',
  'yogurt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/330px-Joghurt.jpg',
  'butter': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/%C5%A0v%C3%A9dsk%C3%BD_kol%C3%A1%C4%8D_naruby_904_%28cropped%29.JPG/330px-%C5%A0v%C3%A9dsk%C3%BD_kol%C3%A1%C4%8D_naruby_904_%28cropped%29.JPG',
  'ice cream': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg/330px-Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg',
  'chocolate': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Three_Bars_%281%29.jpg/330px-Three_Bars_%281%29.jpg',
  'cake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Pound_layer_cake.jpg/330px-Pound_layer_cake.jpg',
  'cheesecake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/330px-Baked_cheesecake_with_raspberries_and_blueberries.jpg',
  'cookie': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Choco_chip_cookie.png/330px-Choco_chip_cookie.png',
  'doughnut': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glazed-Donut.jpg/330px-Glazed-Donut.jpg',
  'pie': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Top_down_view_of_peach_pie_%28722379748%29.jpg/330px-Top_down_view_of_peach_pie_%28722379748%29.jpg',
  'pancake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg/330px-Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg',
  'waffle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Waffles_with_Strawberries.jpg/330px-Waffles_with_Strawberries.jpg',
  'apple': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/330px-Pink_lady_and_cross_section.jpg',
  'banana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Bananavarieties.jpg/330px-Bananavarieties.jpg',
  'orange': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
  'strawberry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/330px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg',
  'blueberry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Blueberries.jpg/330px-Blueberries.jpg',
  'raspberry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Raspberry_-_halved_%28Rubus_idaeus%29.jpg/330px-Raspberry_-_halved_%28Rubus_idaeus%29.jpg',
  'grape': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Grapes%2C_Rostov-on-Don%2C_Russia.jpg/330px-Grapes%2C_Rostov-on-Don%2C_Russia.jpg',
  'mango': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/330px-Mangos_-_single_and_halved.jpg',
  'pineapple': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/330px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg',
  'watermelon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg/330px-Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg',
  'peach': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg',
  'pear': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pears.jpg/330px-Pears.jpg',
  'avocado': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Persea_americana_fruit_2.JPG/330px-Persea_americana_fruit_2.JPG',
  'fruit': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Fruit_Platter-_Seasonal_Fruits.jpg/330px-Fruit_Platter-_Seasonal_Fruits.jpg',
  'potato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/330px-Patates.jpg',
  'french fries': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/French_Fries.JPG/330px-French_Fries.JPG',
  'sweet potato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ipomoea_batatas_006.JPG/330px-Ipomoea_batatas_006.JPG',
  'tomato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg',
  'carrot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/330px-Vegetable-Carrot-Bundle-wStalks.jpg',
  'broccoli': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/330px-Broccoli_and_cross_section_edit.jpg',
  'spinach': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg/330px-Spinacia_oleracea_Spinazie_bloeiend.jpg',
  'lettuce': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Iceberg_lettuce_in_SB.jpg/330px-Iceberg_lettuce_in_SB.jpg',
  'cucumber': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/330px-ARS_cucumber.jpg',
  'onion': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/330px-Mixed_onions.jpg',
  'pepper': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/330px-Green-Yellow-Red-Pepper-2009.jpg',
  'mushroom': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Edible_fungi_in_basket_2009_G1_%28cropped%29.jpg/330px-Edible_fungi_in_basket_2009_G1_%28cropped%29.jpg',
  'corn': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/VegCorn.jpg/330px-VegCorn.jpg',
  'peas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Peas_in_pods_-_Studio.jpg/330px-Peas_in_pods_-_Studio.jpg',
  'vegetable': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Marketvegetables.jpg/330px-Marketvegetables.jpg',
  'beans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/French_beans_J1.JPG/330px-French_beans_J1.JPG',
  'lentils': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/3_types_of_lentil.png/330px-3_types_of_lentil.png',
  'chickpeas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chickpea_BNC.jpg/330px-Chickpea_BNC.jpg',
  'tofu': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG/330px-Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG',
  'hummus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Lebanese_style_hummus.jpg/330px-Lebanese_style_hummus.jpg',
  'peanut butter': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/2020-03-24_20_57_22_An_open_jar_of_Skippy_Creamy_Peanut_Butter_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg/330px-2020-03-24_20_57_22_An_open_jar_of_Skippy_Creamy_Peanut_Butter_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg',
  'peanut': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Arachis_hypogaea_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-163.jpg/330px-Arachis_hypogaea_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-163.jpg',
  'almond': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg/330px-Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg',
  'walnut': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Walnuts_-_whole_and_open_with_halved_kernel.jpg/330px-Walnuts_-_whole_and_open_with_halved_kernel.jpg',
  'cashew': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cashew_apples.jpg/330px-Cashew_apples.jpg',
  'nuts': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Mixed_nuts_small_white1.jpg/330px-Mixed_nuts_small_white1.jpg',
  'oatmeal': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Oatmeal.jpg/330px-Oatmeal.jpg',
  'cereal': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/NCI_Visuals_Food_Meal_Breakfast.jpg/330px-NCI_Visuals_Food_Meal_Breakfast.jpg',
  'granola': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg/330px-Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg',
  'honey': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Runny_hunny.jpg/330px-Runny_hunny.jpg',
  'sugar': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sucre_blanc_cassonade_complet_rapadura.jpg/330px-Sucre_blanc_cassonade_complet_rapadura.jpg',
  'olive oil': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Oliven_V1.jpg/330px-Oliven_V1.jpg',
  'coffee': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Latte_and_dark_coffee.jpg/330px-Latte_and_dark_coffee.jpg',
  'tea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Longjing_tea_steeping_in_gaiwan.jpg/330px-Longjing_tea_steeping_in_gaiwan.jpg',
  'juice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Orange_juice_1.jpg/330px-Orange_juice_1.jpg',
  'smoothie': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Kiwi_Smoothie.jpg/330px-Kiwi_Smoothie.jpg',
  'soda': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Tumbler_of_cola_with_ice.jpg/330px-Tumbler_of_cola_with_ice.jpg',
  'water': 'https://upload.wikimedia.org/wikipedia/commons/0/02/Stilles_Mineralwasser.jpg',
  'beer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Jeju_beer_09_%28cropped%29.jpg/330px-Jeju_beer_09_%28cropped%29.jpg',
  'wine': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Red_and_white_wine_in_glass.jpg/330px-Red_and_white_wine_in_glass.jpg',
  'protein shake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Whey_powder.jpg/330px-Whey_powder.jpg',
  'protein bar': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Three_protein_bars%2C_two_cut_in_half.jpg/330px-Three_protein_bars%2C_two_cut_in_half.jpg',
  'popcorn': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Popcorn_-_Studio_-_2011.jpg/330px-Popcorn_-_Studio_-_2011.jpg',
  'potato chips': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Potato-Chips.jpg/330px-Potato-Chips.jpg',
  'pretzel': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/BrezelnSalz02_%28cropped%29.JPG/330px-BrezelnSalz02_%28cropped%29.JPG',
  'biryani': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/330px-%22Hyderabadi_Dum_Biryani%22.jpg',
  'naan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Annapurna_Naan.jpg/330px-Annapurna_Naan.jpg',
  'paneer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Panir_Paneer_Indian_cheese_fresh.jpg/330px-Panir_Paneer_Indian_cheese_fresh.jpg',
  'samosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg/330px-Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg',
  'dosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Dosa_at_Sri_Ganesha_Restauran%2C_Bangkok_%2844570742744%29.jpg/330px-Dosa_at_Sri_Ganesha_Restauran%2C_Bangkok_%2844570742744%29.jpg',
  'kebab': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Lula_kebab_2.jpg/330px-Lula_kebab_2.jpg',
  'shawarma': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Shawarma_2.jpg/330px-Shawarma_2.jpg',
  'falafel': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Falafels_2.jpg/330px-Falafels_2.jpg',
  'dumpling': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg/330px-HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg',
  'pad thai': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Phat_Thai_kung_Chang_Khien_street_stall.jpg/330px-Phat_Thai_kung_Chang_Khien_street_stall.jpg',
  'pho': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Bowl_of_Meatball_pho.jpg/330px-Bowl_of_Meatball_pho.jpg',
  'risotto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Risotto_with_speck_and_goat_cheese_%286101067436%29.jpg/330px-Risotto_with_speck_and_goat_cheese_%286101067436%29.jpg',
  'rice and beans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rice_and_beans%2C_Hotel_in_Itatiaia.jpeg/330px-Rice_and_beans%2C_Hotel_in_Itatiaia.jpeg',
  'tomato soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Tomato_soup%2C_plant-based_%2844040252791%29.jpg/330px-Tomato_soup%2C_plant-based_%2844040252791%29.jpg',
  'chicken soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Chicken_Noodle_Soup.jpg/330px-Chicken_Noodle_Soup.jpg',
  'lentil soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/EgFoodLentilSoup.jpg/330px-EgFoodLentilSoup.jpg',
  'onion soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Soupe_%C3%A0_l%27oignon.jpg/330px-Soupe_%C3%A0_l%27oignon.jpg',
  'vegetable soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Vegetable_udon_noodle_soup.jpg/330px-Vegetable_udon_noodle_soup.jpg',
  'noodle soup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nabeyaku_ramen_%28cropped%29.jpg/330px-Nabeyaku_ramen_%28cropped%29.jpg',
  'minestrone': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Minestrone_soup_%285%29.jpg/330px-Minestrone_soup_%285%29.jpg',
  'clam chowder': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Quail_07_bg_041506.jpg/330px-Quail_07_bg_041506.jpg',
  'borscht': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Borscht_served.jpg/330px-Borscht_served.jpg',
  'gumbo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Gumbo.JPG/330px-Gumbo.JPG',
  'pozole': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Green_pozole%2C_dressed_%2829161841908%29_%28cropped%29.jpg/330px-Green_pozole%2C_dressed_%2829161841908%29_%28cropped%29.jpg',
  'congee': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Chinese_rice_congee.jpg/330px-Chinese_rice_congee.jpg',
  'wonton': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Pork_Steamed_Wontons.jpg/330px-Pork_Steamed_Wontons.jpg',
  'chili': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Bowl_of_chili.jpg/330px-Bowl_of_chili.jpg',
  'broth': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Broth_hg.jpg/330px-Broth_hg.jpg',
  'pasta salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Pasta_salad_closeup.JPG/330px-Pasta_salad_closeup.JPG',
  'macaroni salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Macaroni_salad.jpg/330px-Macaroni_salad.jpg',
  'potato salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Potato_salad_%281%29.jpg/330px-Potato_salad_%281%29.jpg',
  'coleslaw': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/2015-12-20_Spitzkohlsalat_mit_M%C3%B6hren_anagoria.JPG/330px-2015-12-20_Spitzkohlsalat_mit_M%C3%B6hren_anagoria.JPG',
  'caesar salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Caesar_salad_%282%29.jpg/330px-Caesar_salad_%282%29.jpg',
  'greek salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Greece_Food_Horiatiki.JPG/330px-Greece_Food_Horiatiki.JPG',
  'fruit salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Fruktsallad_%28Fruit_salad%29.jpg/330px-Fruktsallad_%28Fruit_salad%29.jpg',
  'tuna salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Tuna_fish_sandwiches_for_the_National_School_Lunch_Program_%281%29.jpg/330px-Tuna_fish_sandwiches_for_the_National_School_Lunch_Program_%281%29.jpg',
  'egg salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Egg_salad_01.jpg/330px-Egg_salad_01.jpg',
  'chicken salad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flickr_sa_ku_ra_10556400--Chicken_salad.jpg/330px-Flickr_sa_ku_ra_10556400--Chicken_salad.jpg',
  'chicken feet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Chicken_feet.jpg/330px-Chicken_feet.jpg',
  'gizzard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Gizzard_of_Chicken.JPG/330px-Gizzard_of_Chicken.JPG',
  'liver': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Pig%27s_liver_with_sauteed_onion.jpg/330px-Pig%27s_liver_with_sauteed_onion.jpg',
  'roast beef': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rostas_%28ready_and_served%29.JPG/330px-Rostas_%28ready_and_served%29.JPG',
  'ground beef': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Hackfleisch-1.jpg/330px-Hackfleisch-1.jpg',
  'meatball': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Soup_with_meatballs-01.jpg/330px-Soup_with_meatballs-01.jpg',
  'meatloaf': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/MeatloafWithSauce.jpg/330px-MeatloafWithSauce.jpg',
  'pastrami': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Ben%27s_Best_Deli_Rego_Park_pastrami_sandwich.jpg/330px-Ben%27s_Best_Deli_Rego_Park_pastrami_sandwich.jpg',
  'salami': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Salame_di_Sauris.jpg/330px-Salame_di_Sauris.jpg',
  'pepperoni': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Pepperoni_Pizza_%2829204589095%29.jpg/330px-Pepperoni_Pizza_%2829204589095%29.jpg',
  'jerky': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Jerky_%281%29.jpg/330px-Jerky_%281%29.jpg',
  'ribs': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Balinese_Roasted_Pork_Ribs_-_Iga_Babi_Panggang_Bali.JPG/330px-Balinese_Roasted_Pork_Ribs_-_Iga_Babi_Panggang_Bali.JPG',
  'brisket': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Brisketphoto.jpg/330px-Brisketphoto.jpg',
  'duck': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/And_%2824559569447%29.jpg/330px-And_%2824559569447%29.jpg',
  'venison': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Venison_Steaks.jpg/330px-Venison_Steaks.jpg',
  'crab meat': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Ristet_br%C3%B8d_med_krabbekl%C3%B8er_%284898535215%29.jpg/330px-Ristet_br%C3%B8d_med_krabbekl%C3%B8er_%284898535215%29.jpg',
  'calamari': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Babbo-_Squid_Ink_pasta_with_green_chilis%2C_rock_shrimp_and_guanciale.jpg/330px-Babbo-_Squid_Ink_pasta_with_green_chilis%2C_rock_shrimp_and_guanciale.jpg',
  'fish and chips': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Fish_and_chips_blackpool.jpg/330px-Fish_and_chips_blackpool.jpg',
  'sashimi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/241109_Shigaraki_ware_Koga_Shiga_pref_Japan01s3.jpg/330px-241109_Shigaraki_ware_Koga_Shiga_pref_Japan01s3.jpg',
  'tempura': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Tempura_01.jpg/330px-Tempura_01.jpg',
  'scrambled eggs': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Scrambed_eggs.jpg/330px-Scrambed_eggs.jpg',
  'boiled egg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Soft-boiled-egg.jpg/330px-Soft-boiled-egg.jpg',
  'fried egg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Fried_Egg_2.jpg/330px-Fried_Egg_2.jpg',
  'deviled egg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/0.2014_Ostereier_zum_Fr%C3%BChst%C3%BCck%2C_Beskiden%2C_Nowotaniec.jpg/330px-0.2014_Ostereier_zum_Fr%C3%BChst%C3%BCck%2C_Beskiden%2C_Nowotaniec.jpg',
  'cheddar': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Somerset-Cheddar.jpg/330px-Somerset-Cheddar.jpg',
  'mozzarella': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mozzarella_di_bufala3.jpg/330px-Mozzarella_di_bufala3.jpg',
  'parmesan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Parmigiano_Reggiano%2C_Italien%2C_Europ%C3%A4ische_Union.jpg/330px-Parmigiano_Reggiano%2C_Italien%2C_Europ%C3%A4ische_Union.jpg',
  'feta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Feta_Cheese.jpg/330px-Feta_Cheese.jpg',
  'cottage cheese': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Cottagecheese200px.jpg/330px-Cottagecheese200px.jpg',
  'cream cheese': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Philly_cream_cheese.jpg/330px-Philly_cream_cheese.jpg',
  'sour cream': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Bowl_of_chili_with_sour_cream_and_cheese.jpg/330px-Bowl_of_chili_with_sour_cream_and_cheese.jpg',
  'whipped cream': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Hot_chocolate_%282%29.jpg/330px-Hot_chocolate_%282%29.jpg',
  'cream': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/01_Mmm..._Apple_Crisp_with_Whipped_Cream.jpg/330px-01_Mmm..._Apple_Crisp_with_Whipped_Cream.jpg',
  'milkshake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Strawberry_milk_shake_%28cropped%29.jpg/330px-Strawberry_milk_shake_%28cropped%29.jpg',
  'pound cake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Pound_cake_2.jpg/330px-Pound_cake_2.jpg',
  'sponge cake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Victoria_Sponges.jpg/330px-Victoria_Sponges.jpg',
  'carrot cake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Carrot_cake_at_America_Graffiti_%28cropped%29.jpg/330px-Carrot_cake_at_America_Graffiti_%28cropped%29.jpg',
  'brownie': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Chocolatebrownie.JPG/330px-Chocolatebrownie.JPG',
  'muffin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/02116jfMuffins_in_Philippinesfvf_02.jpg/330px-02116jfMuffins_in_Philippinesfvf_02.jpg',
  'cupcake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Cupcakes%2C_chocolate_and_strawberry_flavour.jpg/330px-Cupcakes%2C_chocolate_and_strawberry_flavour.jpg',
  'pudding': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Blanc-manger_on_glass_platter%2C_full_view.jpg/330px-Blanc-manger_on_glass_platter%2C_full_view.jpg',
  'custard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Custard.jpg/330px-Custard.jpg',
  'gelatin dessert': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Rainbow-Jello-Cut-2004-Jul-30.jpg/330px-Rainbow-Jello-Cut-2004-Jul-30.jpg',
  'macaron': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/VanillaMacaron.jpg/330px-VanillaMacaron.jpg',
  'tart': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Raspberry_tart.jpg/330px-Raspberry_tart.jpg',
  'scone': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Scone_varieties.jpg/330px-Scone_varieties.jpg',
  'french toast': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/FrenchToast.JPG/330px-FrenchToast.JPG',
  'crepe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Crepes_dsc07085.jpg/330px-Crepes_dsc07085.jpg',
  'churro': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Chocolate_con_churros_%2827343655726%29.jpg/330px-Chocolate_con_churros_%2827343655726%29.jpg',
  'baklava': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Baklava%281%29.png/330px-Baklava%281%29.png',
  'tiramisu': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Tiramisu_-_Raffaele_Diomede.jpg/330px-Tiramisu_-_Raffaele_Diomede.jpg',
  'porridge': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Oatmeal_%281%29.jpg/330px-Oatmeal_%281%29.jpg',
  'grits': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Grits1.jpg/330px-Grits1.jpg',
  'polenta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Cotechino-Servito-Polenta-Lenticchie.jpg/330px-Cotechino-Servito-Polenta-Lenticchie.jpg',
  'bulgur': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Bulgur.jpg/330px-Bulgur.jpg',
  'rice noodles': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Rice_vermicelli.jpg/330px-Rice_vermicelli.jpg',
  'glutinous rice': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Chapssal_%28glutinous_rice%29.jpg/330px-Chapssal_%28glutinous_rice%29.jpg',
  'rice pudding': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kheer_with_condensed_milk..JPG/330px-Kheer_with_condensed_milk..JPG',
  'sourdough': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Home_made_sour_dough_bread.jpg/330px-Home_made_sour_dough_bread.jpg',
  'rye bread': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Market_Bread%2C_Riga%2C_Latvia.jpg/330px-Market_Bread%2C_Riga%2C_Latvia.jpg',
  'pita': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Pita_Bread.jpg/330px-Pita_Bread.jpg',
  'roti': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/2020-05-08_19_34_28_Chapati_being_made_in_a_pan_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg/330px-2020-05-08_19_34_28_Chapati_being_made_in_a_pan_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg',
  'cornbread': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Skillet_cornbread_%28cropped%29.jpg/330px-Skillet_cornbread_%28cropped%29.jpg',
  'biscuit': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Bourbon_and_Custard_Cream.jpeg/330px-Bourbon_and_Custard_Cream.jpeg',
  'baguette': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Baguettes%2C_Paris%2C_France_-_panoramio.jpg/330px-Baguettes%2C_Paris%2C_France_-_panoramio.jpg',
  'garlic bread': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Garlicbread.jpg/330px-Garlicbread.jpg',
  'cauliflower': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Chou-fleur_02.jpg/330px-Chou-fleur_02.jpg',
  'cabbage': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/330px-Cabbage_and_cross_section_on_white.jpg',
  'kale': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Boerenkool.jpg/330px-Boerenkool.jpg',
  'celery': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Celery_1.jpg/330px-Celery_1.jpg',
  'zucchini': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/330px-CSA-Striped-Zucchini.jpg',
  'eggplant': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/330px-Solanum_melongena_24_08_2012_%281%29.JPG',
  'beet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Detroitdarkredbeets.png/330px-Detroitdarkredbeets.png',
  'pumpkin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/FrenchMarketPumpkinsB.jpg/330px-FrenchMarketPumpkinsB.jpg',
  'squash': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cucurbita_moschata_Butternut_2012_G2.jpg/330px-Cucurbita_moschata_Butternut_2012_G2.jpg',
  'brussels sprouts': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Brussels_sprout_closeup.jpg/330px-Brussels_sprout_closeup.jpg',
  'green beans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Heaps_of_beans.jpg/330px-Heaps_of_beans.jpg',
  'okra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Hong_Kong_Okra_Aug_25_2012.JPG/330px-Hong_Kong_Okra_Aug_25_2012.JPG',
  'artichoke': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Artichoke_J1.jpg/330px-Artichoke_J1.jpg',
  'garlic': 'https://upload.wikimedia.org/wikipedia/commons/3/39/Allium_sativum_Woodwill_1793.jpg',
  'ginger': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Koeh-146-no_text.jpg/330px-Koeh-146-no_text.jpg',
  'olive': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Olivesfromjordan.jpg/330px-Olivesfromjordan.jpg',
  'pickle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Pickle.jpg/330px-Pickle.jpg',
  'kimchi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Various_kimchi.jpg/330px-Various_kimchi.jpg',
  'hash browns': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mmm..._sliders_and_deep_fried_hash_browns_%287958927842%29.jpg/330px-Mmm..._sliders_and_deep_fried_hash_browns_%287958927842%29.jpg',
  'mashed potato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sous_vide_mashed_potatoes.jpg/330px-Sous_vide_mashed_potatoes.jpg',
  'baked potato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/BakedPotatoWithButter.jpg/330px-BakedPotatoWithButter.jpg',
  'cherry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cherry_season_%2848216568227%29.jpg/330px-Cherry_season_%2848216568227%29.jpg',
  'plum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Plums_African_Rose_-_whole%2C_halved_and_slice.jpg/330px-Plums_African_Rose_-_whole%2C_halved_and_slice.jpg',
  'apricot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Apricot_and_cross_section.jpg/330px-Apricot_and_cross_section.jpg',
  'kiwi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Actinidia_fruits.jpg/330px-Actinidia_fruits.jpg',
  'papaya': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg/330px-Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg',
  'pomegranate': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/330px-Pomegranate_Juice_%282019%29.jpg',
  'fig': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ficus_carica_L%2C_1771.jpg/330px-Ficus_carica_L%2C_1771.jpg',
  'lemon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/330px-P1030323.JPG',
  'lime': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Lime_Blossom.jpg/330px-Lime_Blossom.jpg',
  'grapefruit': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Grapefruits_-_whole-halved-segments.jpg/330px-Grapefruits_-_whole-halved-segments.jpg',
  'cantaloupe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Meloen_vrucht_met_bloem.jpg/330px-Meloen_vrucht_met_bloem.jpg',
  'coconut': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg/330px-Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg',
  'cranberry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cranberry_bog.jpg/330px-Cranberry_bog.jpg',
  'blackberry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ripe%2C_ripening%2C_and_green_blackberries.jpg/330px-Ripe%2C_ripening%2C_and_green_blackberries.jpg',
  'raisin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Raisins_01.jpg/330px-Raisins_01.jpg',
  'salsa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Various_salsas.jpg/330px-Various_salsas.jpg',
  'guacamole': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Guacamole_IMGP1271.jpg/330px-Guacamole_IMGP1271.jpg',
  'ketchup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Ketchup_20160918_181342_%28cropped%29.jpg/330px-Ketchup_20160918_181342_%28cropped%29.jpg',
  'mustard': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mustard.JPG/330px-Mustard.JPG',
  'mayonnaise': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Mayonnaise_%281%29.jpg/330px-Mayonnaise_%281%29.jpg',
  'soy sauce': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Soy_sauce_2.jpg/330px-Soy_sauce_2.jpg',
  'gravy': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Wine_sauces_on_the_sauceboat.jpg/330px-Wine_sauces_on_the_sauceboat.jpg',
  'pesto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/BasilPesto.JPG/330px-BasilPesto.JPG',
  'jam': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Fruits_jam_variants.jpg/330px-Fruits_jam_variants.jpg',
  'syrup': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Maple_syrup.jpg/330px-Maple_syrup.jpg',
  'sauce': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Lunch_sauces.jpg/330px-Lunch_sauces.jpg',
  'edamame': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Edamame_by_Zesmerelda_in_Chicago.jpg/330px-Edamame_by_Zesmerelda_in_Chicago.jpg',
  'black beans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Black_beans_%281126927794%29.jpg/330px-Black_beans_%281126927794%29.jpg',
  'baked beans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Baked_beans_in_tomato_sauce.jpg/330px-Baked_beans_in_tomato_sauce.jpg',
  'pistachio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Pistachio_vera.jpg/330px-Pistachio_vera.jpg',
  'pecan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Carya_illinoinensis.jpg/330px-Carya_illinoinensis.jpg',
  'sunflower seeds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Sunflower_Seeds_Kaldari.jpg/330px-Sunflower_Seeds_Kaldari.jpg',
  'chia seeds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Seed_of_chia_%28Salvia_hispanica%29Salvia_hispanica_group.jpg/330px-Seed_of_chia_%28Salvia_hispanica%29Salvia_hispanica_group.jpg',
  'sesame': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Sesamum_indicum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-129.jpg/330px-Sesamum_indicum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-129.jpg',
  'tempeh': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Tempeh_%288681605421%29.jpg/330px-Tempeh_%288681605421%29.jpg',
  'soy milk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/004-soymilk.jpg/330px-004-soymilk.jpg',
  'almond milk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Home-made_almond_milk%2C_November_2012.jpg/330px-Home-made_almond_milk%2C_November_2012.jpg',
  'oat milk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Oat_milk_glass_and_bottles.jpg/330px-Oat_milk_glass_and_bottles.jpg',
  'quesadilla': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Empanada_flor_de_Calabaza.jpg/330px-Empanada_flor_de_Calabaza.jpg',
  'nachos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Nachos-cheese.jpg/330px-Nachos-cheese.jpg',
  'enchilada': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Enchilada_Rice_Beans.jpg/330px-Enchilada_Rice_Beans.jpg',
  'tamale': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tamale_Oaxaque%C3%B1o.jpg/330px-Tamale_Oaxaque%C3%B1o.jpg',
  'empanada': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Tapa_de_empanadillitas.JPG/330px-Tapa_de_empanadillitas.JPG',
  'spring roll': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Spring_Rolls_%283357696061%29.jpg/330px-Spring_Rolls_%283357696061%29.jpg',
  'chow mein': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Homemade_Chow_mein_with_shrimps_and_meat_with_a_choy_and_Choung.jpg/330px-Homemade_Chow_mein_with_shrimps_and_meat_with_a_choy_and_Choung.jpg',
  'bibimbap': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/330px-Dolsot-bibimbap.jpg',
  'teriyaki': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/22nd_June_2012_Teriyaki_Duck.jpg/330px-22nd_June_2012_Teriyaki_Duck.jpg',
  'dim sum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Chinese_DimSum_%289023590541%29.jpg/330px-Chinese_DimSum_%289023590541%29.jpg',
  'satay': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Sate_Udang.JPG/330px-Sate_Udang.JPG',
  'gyro': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pita_giros.JPG/330px-Pita_giros.JPG',
  'paella': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/01_Paella_Valenciana_original.jpg/330px-01_Paella_Valenciana_original.jpg',
  'gnocchi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Gnocchi_di_ricotta_burro_e_salvia.jpg/330px-Gnocchi_di_ricotta_burro_e_salvia.jpg',
  'ravioli': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg/330px-Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg',
  'carbonara': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Espaguetis_carbonara.jpg/330px-Espaguetis_carbonara.jpg',
  'mac and cheese': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Original_Mac_n_Cheese_.jpg/330px-Original_Mac_n_Cheese_.jpg',
  'bolognese': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Tagliatelle_al_rag%C3%B9_%28image_modified%29.jpg/330px-Tagliatelle_al_rag%C3%B9_%28image_modified%29.jpg',
  'shepherds pie': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg/330px-Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg',
  'pot pie': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/ChickenpotpieswholeFeb09.jpg/330px-ChickenpotpieswholeFeb09.jpg',
  'quiche': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Quiche.jpg/330px-Quiche.jpg',
  'stir fry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Making_Stir-Fry_%283286445383%29.jpg/330px-Making_Stir-Fry_%283286445383%29.jpg',
  'hot chocolate': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/After_The_St._Patrick%27s_Parade_Late_Lunch_%40_Lemon%2C_Dawson_Street%2C_Dublin%2C_Rep._Of_Ireland_A_Fine_Tradition%21_%286992614913%29.jpg/330px-After_The_St._Patrick%27s_Parade_Late_Lunch_%40_Lemon%2C_Dawson_Street%2C_Dublin%2C_Rep._Of_Ireland_A_Fine_Tradition%21_%286992614913%29.jpg',
  'lemonade': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Lemonade_-_27682817724.jpg/330px-Lemonade_-_27682817724.jpg',
  'energy drink': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Energydrinks.jpg/330px-Energydrinks.jpg',
  'kombucha': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kombucha_Mature.jpg/330px-Kombucha_Mature.jpg',
  'cheeseburger': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cheeseburger.jpg/330px-Cheeseburger.jpg',
  'grilled cheese': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Cheddar_cheese_sandwich.jpg/330px-Cheddar_cheese_sandwich.jpg',
  'blt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Mmm..._BLT_for_me%21_%285487341380%29.jpg/330px-Mmm..._BLT_for_me%21_%285487341380%29.jpg',
  'club sandwich': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Club_sandwich_at_Caf%C3%A9_Picnic.jpg/330px-Club_sandwich_at_Caf%C3%A9_Picnic.jpg',
  'sausage roll': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Sausage_roll_-_One_Market%2C_One_Garden_Brighton_%28cropped%29.jpg/330px-Sausage_roll_-_One_Market%2C_One_Garden_Brighton_%28cropped%29.jpg',
};

/** Longest keys first so "brown rice" wins over "rice" during substring matching. */
export const CURATED_FOOD_KEYS_BY_SPECIFICITY: string[] = Object.keys(CURATED_FOOD_IMAGES).sort(
  (a, b) => b.length - a.length
);
