/**
 * Self-hosted food thumbnails, keyed by food concept.
 *
 * GENERATED FILE — do not edit by hand. Rebuild with:
 *   node --import tsx scripts/buildFoodImageAssets.ts
 *
 * Paths are served by express.static from public/food-images. They are returned to
 * clients as-is; the app resolves relative paths against SERVER_URL.
 *
 * Attribution for every file lives in public/food-images/credits.json.
 *
 * Generated 2026-09-04 with 312 concepts.
 */
export const LOCAL_FOOD_IMAGES: Record<string, string> = {
  'almond': '/food-images/almond.webp',
  'almond milk': '/food-images/almond-milk.webp',
  'apple': '/food-images/apple.webp',
  'apricot': '/food-images/apricot.webp',
  'artichoke': '/food-images/artichoke.webp',
  'avocado': '/food-images/avocado.webp',
  'bacon': '/food-images/bacon.webp',
  'bagel': '/food-images/bagel.webp',
  'baguette': '/food-images/baguette.webp',
  'baked beans': '/food-images/baked-beans.webp',
  'baked potato': '/food-images/baked-potato.webp',
  'baklava': '/food-images/baklava.webp',
  'banana': '/food-images/banana.webp',
  'beans': '/food-images/beans.webp',
  'beef': '/food-images/beef.webp',
  'beer': '/food-images/beer.webp',
  'beet': '/food-images/beet.webp',
  'bibimbap': '/food-images/bibimbap.webp',
  'biryani': '/food-images/biryani.webp',
  'biscuit': '/food-images/biscuit.webp',
  'black beans': '/food-images/black-beans.webp',
  'blackberry': '/food-images/blackberry.webp',
  'blt': '/food-images/blt.webp',
  'blueberry': '/food-images/blueberry.webp',
  'boiled egg': '/food-images/boiled-egg.webp',
  'bolognese': '/food-images/bolognese.webp',
  'borscht': '/food-images/borscht.webp',
  'bread': '/food-images/bread.webp',
  'brisket': '/food-images/brisket.webp',
  'broccoli': '/food-images/broccoli.webp',
  'broth': '/food-images/broth.webp',
  'brown rice': '/food-images/brown-rice.webp',
  'brownie': '/food-images/brownie.webp',
  'brussels sprouts': '/food-images/brussels-sprouts.webp',
  'bulgur': '/food-images/bulgur.webp',
  'burrito': '/food-images/burrito.webp',
  'butter': '/food-images/butter.webp',
  'cabbage': '/food-images/cabbage.webp',
  'caesar salad': '/food-images/caesar-salad.webp',
  'cake': '/food-images/cake.webp',
  'calamari': '/food-images/calamari.webp',
  'cantaloupe': '/food-images/cantaloupe.webp',
  'carbonara': '/food-images/carbonara.webp',
  'carrot': '/food-images/carrot.webp',
  'carrot cake': '/food-images/carrot-cake.webp',
  'cashew': '/food-images/cashew.webp',
  'cauliflower': '/food-images/cauliflower.webp',
  'celery': '/food-images/celery.webp',
  'cereal': '/food-images/cereal.webp',
  'cheddar': '/food-images/cheddar.webp',
  'cheese': '/food-images/cheese.webp',
  'cheeseburger': '/food-images/cheeseburger.webp',
  'cheesecake': '/food-images/cheesecake.webp',
  'cherry': '/food-images/cherry.webp',
  'chia seeds': '/food-images/chia-seeds.webp',
  'chicken': '/food-images/chicken.webp',
  'chicken feet': '/food-images/chicken-feet.webp',
  'chicken salad': '/food-images/chicken-salad.webp',
  'chicken soup': '/food-images/chicken-soup.webp',
  'chicken wings': '/food-images/chicken-wings.webp',
  'chickpeas': '/food-images/chickpeas.webp',
  'chili': '/food-images/chili.webp',
  'chocolate': '/food-images/chocolate.webp',
  'chow mein': '/food-images/chow-mein.webp',
  'churro': '/food-images/churro.webp',
  'clam chowder': '/food-images/clam-chowder.webp',
  'club sandwich': '/food-images/club-sandwich.webp',
  'coconut': '/food-images/coconut.webp',
  'coffee': '/food-images/coffee.webp',
  'coleslaw': '/food-images/coleslaw.webp',
  'congee': '/food-images/congee.webp',
  'cookie': '/food-images/cookie.webp',
  'corn': '/food-images/corn.webp',
  'cornbread': '/food-images/cornbread.webp',
  'cottage cheese': '/food-images/cottage-cheese.webp',
  'couscous': '/food-images/couscous.webp',
  'crab meat': '/food-images/crab-meat.webp',
  'cranberry': '/food-images/cranberry.webp',
  'cream': '/food-images/cream.webp',
  'cream cheese': '/food-images/cream-cheese.webp',
  'crepe': '/food-images/crepe.webp',
  'croissant': '/food-images/croissant.webp',
  'cucumber': '/food-images/cucumber.webp',
  'cupcake': '/food-images/cupcake.webp',
  'curry': '/food-images/curry.webp',
  'custard': '/food-images/custard.webp',
  'deviled egg': '/food-images/deviled-egg.webp',
  'dim sum': '/food-images/dim-sum.webp',
  'dosa': '/food-images/dosa.webp',
  'doughnut': '/food-images/doughnut.webp',
  'duck': '/food-images/duck.webp',
  'dumpling': '/food-images/dumpling.webp',
  'edamame': '/food-images/edamame.webp',
  'egg': '/food-images/egg.webp',
  'egg salad': '/food-images/egg-salad.webp',
  'eggplant': '/food-images/eggplant.webp',
  'empanada': '/food-images/empanada.webp',
  'enchilada': '/food-images/enchilada.webp',
  'energy drink': '/food-images/energy-drink.webp',
  'falafel': '/food-images/falafel.webp',
  'feta': '/food-images/feta.webp',
  'fig': '/food-images/fig.webp',
  'fish': '/food-images/fish.webp',
  'fish and chips': '/food-images/fish-and-chips.webp',
  'french fries': '/food-images/french-fries.webp',
  'french toast': '/food-images/french-toast.webp',
  'fried chicken': '/food-images/fried-chicken.webp',
  'fried egg': '/food-images/fried-egg.webp',
  'fried rice': '/food-images/fried-rice.webp',
  'fruit': '/food-images/fruit.webp',
  'fruit salad': '/food-images/fruit-salad.webp',
  'garlic': '/food-images/garlic.webp',
  'garlic bread': '/food-images/garlic-bread.webp',
  'gelatin dessert': '/food-images/gelatin-dessert.webp',
  'ginger': '/food-images/ginger.webp',
  'gizzard': '/food-images/gizzard.webp',
  'glutinous rice': '/food-images/glutinous-rice.webp',
  'gnocchi': '/food-images/gnocchi.webp',
  'granola': '/food-images/granola.webp',
  'grape': '/food-images/grape.webp',
  'grapefruit': '/food-images/grapefruit.webp',
  'gravy': '/food-images/gravy.webp',
  'greek salad': '/food-images/greek-salad.webp',
  'green beans': '/food-images/green-beans.webp',
  'grilled cheese': '/food-images/grilled-cheese.webp',
  'grits': '/food-images/grits.webp',
  'ground beef': '/food-images/ground-beef.webp',
  'guacamole': '/food-images/guacamole.webp',
  'gumbo': '/food-images/gumbo.webp',
  'gyro': '/food-images/gyro.webp',
  'ham': '/food-images/ham.webp',
  'hamburger': '/food-images/hamburger.webp',
  'hash browns': '/food-images/hash-browns.webp',
  'honey': '/food-images/honey.webp',
  'hot chocolate': '/food-images/hot-chocolate.webp',
  'hot dog': '/food-images/hot-dog.webp',
  'hummus': '/food-images/hummus.webp',
  'ice cream': '/food-images/ice-cream.webp',
  'jam': '/food-images/jam.webp',
  'jerky': '/food-images/jerky.webp',
  'juice': '/food-images/juice.webp',
  'kale': '/food-images/kale.webp',
  'kebab': '/food-images/kebab.webp',
  'ketchup': '/food-images/ketchup.webp',
  'kimchi': '/food-images/kimchi.webp',
  'kiwi': '/food-images/kiwi.webp',
  'kombucha': '/food-images/kombucha.webp',
  'lamb': '/food-images/lamb.webp',
  'lasagna': '/food-images/lasagna.webp',
  'lemon': '/food-images/lemon.webp',
  'lemonade': '/food-images/lemonade.webp',
  'lentil soup': '/food-images/lentil-soup.webp',
  'lentils': '/food-images/lentils.webp',
  'lettuce': '/food-images/lettuce.webp',
  'lime': '/food-images/lime.webp',
  'liver': '/food-images/liver.webp',
  'mac and cheese': '/food-images/mac-and-cheese.webp',
  'macaron': '/food-images/macaron.webp',
  'macaroni': '/food-images/macaroni.webp',
  'macaroni salad': '/food-images/macaroni-salad.webp',
  'mango': '/food-images/mango.webp',
  'mashed potato': '/food-images/mashed-potato.webp',
  'mayonnaise': '/food-images/mayonnaise.webp',
  'meatball': '/food-images/meatball.webp',
  'meatloaf': '/food-images/meatloaf.webp',
  'milk': '/food-images/milk.webp',
  'milkshake': '/food-images/milkshake.webp',
  'minestrone': '/food-images/minestrone.webp',
  'mozzarella': '/food-images/mozzarella.webp',
  'muffin': '/food-images/muffin.webp',
  'mushroom': '/food-images/mushroom.webp',
  'mustard': '/food-images/mustard.webp',
  'naan': '/food-images/naan.webp',
  'nachos': '/food-images/nachos.webp',
  'noodle soup': '/food-images/noodle-soup.webp',
  'noodles': '/food-images/noodles.webp',
  'nuts': '/food-images/nuts.webp',
  'oat milk': '/food-images/oat-milk.webp',
  'oatmeal': '/food-images/oatmeal.webp',
  'okra': '/food-images/okra.webp',
  'olive': '/food-images/olive.webp',
  'olive oil': '/food-images/olive-oil.webp',
  'omelette': '/food-images/omelette.webp',
  'onion': '/food-images/onion.webp',
  'onion soup': '/food-images/onion-soup.webp',
  'orange': '/food-images/orange.webp',
  'pad thai': '/food-images/pad-thai.webp',
  'paella': '/food-images/paella.webp',
  'pancake': '/food-images/pancake.webp',
  'paneer': '/food-images/paneer.webp',
  'papaya': '/food-images/papaya.webp',
  'parmesan': '/food-images/parmesan.webp',
  'pasta': '/food-images/pasta.webp',
  'pasta salad': '/food-images/pasta-salad.webp',
  'pastrami': '/food-images/pastrami.webp',
  'peach': '/food-images/peach.webp',
  'peanut': '/food-images/peanut.webp',
  'peanut butter': '/food-images/peanut-butter.webp',
  'pear': '/food-images/pear.webp',
  'peas': '/food-images/peas.webp',
  'pecan': '/food-images/pecan.webp',
  'pepper': '/food-images/pepper.webp',
  'pepperoni': '/food-images/pepperoni.webp',
  'pesto': '/food-images/pesto.webp',
  'pho': '/food-images/pho.webp',
  'pickle': '/food-images/pickle.webp',
  'pie': '/food-images/pie.webp',
  'pineapple': '/food-images/pineapple.webp',
  'pistachio': '/food-images/pistachio.webp',
  'pita': '/food-images/pita.webp',
  'pizza': '/food-images/pizza.webp',
  'plum': '/food-images/plum.webp',
  'polenta': '/food-images/polenta.webp',
  'pomegranate': '/food-images/pomegranate.webp',
  'popcorn': '/food-images/popcorn.webp',
  'pork': '/food-images/pork.webp',
  'porridge': '/food-images/porridge.webp',
  'pot pie': '/food-images/pot-pie.webp',
  'potato': '/food-images/potato.webp',
  'potato chips': '/food-images/potato-chips.webp',
  'potato salad': '/food-images/potato-salad.webp',
  'pound cake': '/food-images/pound-cake.webp',
  'pozole': '/food-images/pozole.webp',
  'pretzel': '/food-images/pretzel.webp',
  'protein bar': '/food-images/protein-bar.webp',
  'protein shake': '/food-images/protein-shake.webp',
  'pudding': '/food-images/pudding.webp',
  'pumpkin': '/food-images/pumpkin.webp',
  'quesadilla': '/food-images/quesadilla.webp',
  'quiche': '/food-images/quiche.webp',
  'quinoa': '/food-images/quinoa.webp',
  'raisin': '/food-images/raisin.webp',
  'ramen': '/food-images/ramen.webp',
  'raspberry': '/food-images/raspberry.webp',
  'ravioli': '/food-images/ravioli.webp',
  'ribs': '/food-images/ribs.webp',
  'rice': '/food-images/rice.webp',
  'rice and beans': '/food-images/rice-and-beans.webp',
  'rice noodles': '/food-images/rice-noodles.webp',
  'rice pudding': '/food-images/rice-pudding.webp',
  'risotto': '/food-images/risotto.webp',
  'roast beef': '/food-images/roast-beef.webp',
  'roti': '/food-images/roti.webp',
  'rye bread': '/food-images/rye-bread.webp',
  'salad': '/food-images/salad.webp',
  'salami': '/food-images/salami.webp',
  'salmon': '/food-images/salmon.webp',
  'salsa': '/food-images/salsa.webp',
  'samosa': '/food-images/samosa.webp',
  'sandwich': '/food-images/sandwich.webp',
  'sashimi': '/food-images/sashimi.webp',
  'satay': '/food-images/satay.webp',
  'sauce': '/food-images/sauce.webp',
  'sausage': '/food-images/sausage.webp',
  'sausage roll': '/food-images/sausage-roll.webp',
  'scone': '/food-images/scone.webp',
  'scrambled eggs': '/food-images/scrambled-eggs.webp',
  'sesame': '/food-images/sesame.webp',
  'shawarma': '/food-images/shawarma.webp',
  'shepherds pie': '/food-images/shepherds-pie.webp',
  'shrimp': '/food-images/shrimp.webp',
  'smoothie': '/food-images/smoothie.webp',
  'soda': '/food-images/soda.webp',
  'soup': '/food-images/soup.webp',
  'sour cream': '/food-images/sour-cream.webp',
  'sourdough': '/food-images/sourdough.webp',
  'soy milk': '/food-images/soy-milk.webp',
  'soy sauce': '/food-images/soy-sauce.webp',
  'spaghetti': '/food-images/spaghetti.webp',
  'spinach': '/food-images/spinach.webp',
  'sponge cake': '/food-images/sponge-cake.webp',
  'spring roll': '/food-images/spring-roll.webp',
  'squash': '/food-images/squash.webp',
  'steak': '/food-images/steak.webp',
  'stew': '/food-images/stew.webp',
  'stir fry': '/food-images/stir-fry.webp',
  'strawberry': '/food-images/strawberry.webp',
  'sugar': '/food-images/sugar.webp',
  'sunflower seeds': '/food-images/sunflower-seeds.webp',
  'sushi': '/food-images/sushi.webp',
  'sweet potato': '/food-images/sweet-potato.webp',
  'syrup': '/food-images/syrup.webp',
  'taco': '/food-images/taco.webp',
  'tamale': '/food-images/tamale.webp',
  'tart': '/food-images/tart.webp',
  'tea': '/food-images/tea.webp',
  'tempeh': '/food-images/tempeh.webp',
  'tempura': '/food-images/tempura.webp',
  'teriyaki': '/food-images/teriyaki.webp',
  'tiramisu': '/food-images/tiramisu.webp',
  'toast': '/food-images/toast.webp',
  'tofu': '/food-images/tofu.webp',
  'tomato': '/food-images/tomato.webp',
  'tomato soup': '/food-images/tomato-soup.webp',
  'tortilla': '/food-images/tortilla.webp',
  'tuna': '/food-images/tuna.webp',
  'tuna salad': '/food-images/tuna-salad.webp',
  'turkey': '/food-images/turkey.webp',
  'vegetable': '/food-images/vegetable.webp',
  'vegetable soup': '/food-images/vegetable-soup.webp',
  'venison': '/food-images/venison.webp',
  'waffle': '/food-images/waffle.webp',
  'walnut': '/food-images/walnut.webp',
  'water': '/food-images/water.webp',
  'watermelon': '/food-images/watermelon.webp',
  'whipped cream': '/food-images/whipped-cream.webp',
  'white rice': '/food-images/white-rice.webp',
  'wine': '/food-images/wine.webp',
  'wonton': '/food-images/wonton.webp',
  'wrap': '/food-images/wrap.webp',
  'yogurt': '/food-images/yogurt.webp',
  'zucchini': '/food-images/zucchini.webp',
};

/** Longest keys first so "brown rice" wins over "rice" during substring matching. */
export const LOCAL_FOOD_KEYS_BY_SPECIFICITY: string[] = Object.keys(LOCAL_FOOD_IMAGES).sort(
  (a, b) => b.length - a.length
);
